### ISSUE TITLE
Benchmarking NVLM 1.0

### ISSUE THREAD

**Issue by wasiahmad** [HumanEval-V/HumanEval-V-Benchmark#1]
Can you benchmark [NVLM-1.0-D-72B](https://huggingface.co/nvidia/NVLM-D-72B) model on HumanEval-V?

**Comment by zfj1998** [comment]
We have updated the benchmark results for NVLM-1.0-D-72B. Here are the details:

- **Pass@1:** 1.9
- **Pass@10:** 10.7
- **Parsing Success Rate (Greedy Decoding):** 97.2%
- **Parsing Success Rate (Sampling, Temperature 0.8):** 97.3%

Congratulations on the results with your new model! You can view the full results on the [leaderboard](https://humaneval-v.github.io/#leaderboard).
